-- MySQL Script generated by MySQL Workbench
-- 10/26/16 09:18:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web` DEFAULT CHARACTER SET utf8 ;
USE `web` ;

-- -----------------------------------------------------
-- Table `web`.`danhsachhocvienthi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`danhsachhocvienthi` (
  `STT` INT(11) NOT NULL,
  `TenHV` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `TenBaiTap` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ThoiGianNop` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`STT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `web`.`dethi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`dethi` (
  `MaDeThi` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `TenDeThi` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `DuongDanDeThi` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaDeThi`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `web`.`hocvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`hocvien` (
  `Email` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `HoTen` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `GioiTinh` VARCHAR(3) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `SDT` INT(11) NULL DEFAULT NULL,
  `NgaySinh` DATE NULL DEFAULT NULL,
  `HinhAnh` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `web`.`khoahoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`khoahoc` (
  `MaKH` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `TenKH` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `NgayKhaiGiang` DATE NULL DEFAULT NULL,
  `HocPhi` BIGINT(20) NULL DEFAULT NULL,
  `KhaiQuat` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `NoiDung` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaKH`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `web`.`thread`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`thread` (
  `MaThread` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `TenThread` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `NgayTao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`MaThread`))
ENGINE = InnoDB
AUTO_INCREMENT = 1214
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `web`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`users` (
  `UserID` BIGINT(20) NOT NULL,
  `Email` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `Password` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `Role` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `Email_UNIQUE` ON `web`.`users` (`Email` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
